### ISSUE TITLE
Lists stop only two deep.

### ISSUE THREAD

**Issue by blee1170** [CouscousPHP/Couscous#179] opened 2016-09-06 16:07 UTC
I am having problem with lists. In the markdown I have them 3 or 4 deep. But when Couscous renders it, the lists stops at the second one. Is there a flag or something that I can pass so it will render the lists as deep as needed?

I am using the Read the doc template, if that is the problem.

**Comment by mnapoli** [comment] 2016-09-06 16:11
Couscous uses Parsedown to parse the Markdown. Could you try it out in their demo: http://parsedown.org/demo and see if you can reproduce it?

If you can, can you paste an example?

**Comment by blee1170** [comment] 2016-09-06 16:14
I can reproduce it there:

```
* list 1
  * Sub list
    * sub sub list
```

In markdown it lists correctly:
* list 1
  * Sub list
    * sub sub list

In parsedown the sub list and sub sub list are at the same level.

**Comment by blee1170** [comment] 2016-09-06 16:41
Found a work around, looks kind of silly, but it works.

If you add a ordered list to the unordered then you can get more levels:
```
* list 1
    * sub list
       1. sub sub list
```

Which looks like this:

* list 1
    * sub list
       1. sub sub list

Couscous will render it. But its not ideal.

**Comment by mnapoli** [comment] 2016-09-06 17:01
Indeed that's an issue with Parsedown. It seems to require indentation to be 4 spaces (I always use 4 spaces so I didn't see this problem yet):

```
* list 1
    * Sub list
        * sub sub list
```

Could you report this to Parsedown directly?

**Comment by cyberbit** [comment] 2016-09-06 17:02
Looks like this is a pre-existing issue: https://github.com/erusev/parsedown/issues/270. I was able to use the workaround in there to get correct parsing (4 space indentation):

```
* list
    * sub list
        * sub sub list
```

**Comment by blee1170** [comment] 2016-09-06 17:07
Yeah, each sub needs to have 4 spaces indent from the parent, not two. I guess thats okay.

**Comment by mnapoli** [comment] 2016-09-06 17:32
:+1: I'll close the issue here since it's open in Parsedown

**Closed by mnapoli** 2016-09-06 17:32 UTC
